const CartActionTypes = {
	TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
	ADD_ITEM: "ADD_ITEM",
	CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
	CHANGE_ITEM_NUMBER: "CHANGE_ITEM_NUMBER",
};

export default CartActionTypes;
